language: python
python:
  - "3.8"

services:
  - docker

before_script: pip install docker-compose

script:
  - flake8 . --exit-zero
  - docker-compose run app sh -c "python manage.py test && flake8"